### ISSUE TITLE
Abnormal map rendering (curse of extreme nodes)

### ISSUE THREAD

**Issue by denis-yeremich** [abeylot/geodataserver#1]
When viewing the map, as I was able to find out experimentally, there is an abnormal rendering of the polygon/line (anyway way), includes the node with the largest osm-id from the entire imported map data set: in this case, instead of the coordinates of the exact node (in our case - with the maximum osm-id), the coordinates of the node with the smallest osm-id are used.
In case of Russia, for example, the smallest osm-id for node is 2, for Italy it is 1.
![geodataserver](https://github.com/user-attachments/assets/4fb48da5-2161-46d9-8ad8-664b9c3ab310)
![mapnik](https://github.com/user-attachments/assets/56fdf1fb-c11f-4bba-b9af-ab6d911b9bea)

**Comment by abeylot** [comment]
Thats weird !, Ill have a look

**Comment by denis-yereemich** [comment]
There is an empirically found workaround - portion of osm data which have to be included to supress this bug. But it only a workaround, not a solution. Beside that, it could be not alone effect as visible so unvisible.
[sentinel.txt](https://github.com/user-attachments/files/17165598/sentinel.txt)

**Comment by abeylot** [comment]
see commit 34b9b79510a653cf68ccdfd57744f4c7a536cff9 Correct first data node bug
