### ISSUE TITLE
index caused SEGFAULT

### ISSUE THREAD

**Issue by denis-yeremich** [abeylot/geodataserver#4]
Subj on whole map data of France from here https://download.openstreetmap.fr/extracts/europe/france-latest.osm.pbf.
How to reproduce
$ sudo apt install osmium-tool
$ cd build
$ wget https://download.openstreetmap.fr/extracts/europe/france-latest.osm.pbf
$ osmium cat -f xml france-latest.osm.pbf | ./renumber . && osmium cat -f xml france-latest.osm.pbf | ./compile . && osmium cat -f xml france-latest.osm.pbf | ./index .

**Comment by abeylot** [comment]
done
